// config.js

export const CONFIG = {
  CONTRACT_ID: "CCJ3ITE2DBRYX52RGYOJDGWEQW5QFPOAL5NHAARJDCADD3BT2TR7GFV7",
  NETWORK_PASSPHRASE: "Test SDF Network ; September 2015",
  RPC_URL: "https://soroban-testnet.stellar.org",
  ACCOUNT_PUBLIC: "GCTYNEDRO2JPW2P77YUE7DAMLF7DHZ6USEH7VVJJG3SNAEBNSD74N7HA",
  ACCOUNT_SECRET: "SBOKU4QJ3WPSHG7DT3K3I7OCEGRQ6H7PBXCHZH5F4BCBBV44V2DWVP4S", // ⚠️ Testnet only
};
